on:
  push:
    branches:
      - master
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x, 1.22.x, 1.21.x, 1.20.x, 1.19.x, 1.18.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-v1-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-v1-go-

      - name: Test
        run: go test -race -covermode=atomic -coverprofile="profile.cov" ./...

      - name: Send Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.23.x'
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
